# Generated by Django 2.2.11 on 2020-06-10 11:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_auto_20200610_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='transform',
        ),
        migrations.AddField(
            model_name='character',
            name='biome',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='character',
            name='transform_o',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'o': 0.0, 'x': 0.0, 'y': 0.0, 'z': 0.0}),
        ),
        migrations.AddField(
            model_name='character',
            name='transform_x',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'o': 0.0, 'x': 0.0, 'y': 0.0, 'z': 0.0}),
        ),
        migrations.AddField(
            model_name='character',
            name='transform_y',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'o': 0.0, 'x': 0.0, 'y': 0.0, 'z': 0.0}),
        ),
        migrations.AddField(
            model_name='character',
            name='transform_z',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'o': 0.0, 'x': 0.0, 'y': 0.0, 'z': 0.0}),
        ),
    ]
