# Generated by Django 2.2.11 on 2020-06-11 06:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_auto_20200610_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appearance',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'beard': 0, 'body': 1, 'hair': 0}),
        ),
    ]
